config/routes.rb
Rails.application.routes.draw do
  resources :posts
  devise_for :users
  root 'home#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
    belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :destroy, :update]
    def index
      @posts = Post.all
    end
    
    def new 
      @post = Post.new
    end
    
    def create
      post = Post.new(post_params)
      if post.save
          redirect_to posts_path
      else 
          flash[:alert] = "Failed to save"
          redirect_to :back
      end
    end

    def update
      if @post.update(post_params)
        redirect_to posts_path
      else 
        flash[:alert] = "Failed to save"
        redirect_to :back
      end
    end
    
    def edit
    end

    def show
    end
    
    def destroy
      if @post.destroy
        redirect_to posts_path
      else
        flash[:alert] = "Failed to delete"
      end
    end
    
    private
    def post_params
        params.require(:post).permit(:user_id, :title, :content)
    end
    
    def set_post
        @post = Post.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/home/index.html.erb
<div class="jumbotron">
  <h1>Hello, forks!</h1>
  <p>Let's do Upload files! </p>
  <%= link_to "Write post", new_post_path, class: "btn btn-primary btn-lg"%>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand" href="/">숭실대학교 X 멋쟁이사자처럼</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to '게시판', posts_path%></li>
      </ul>
      
      <ul class="nav navbar-nav navbar-right">
        <% unless current_user.present? %>
            <li><%= link_to '로그인', new_user_session_path%></li>
            <li><%= link_to '회원가입', new_user_registration_path%></li>
        <% else %>
            <li><%= link_to '로그아웃', destroy_user_session_path, method: 'delete'%></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  
  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
  
  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

</head>
<body>
<%= render partial: "/layouts/navbar.html.erb" %>
<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/posts/_form.html.erb
<%= flash[:alert] %>
<%= form_for(@post) do |f| %>
    제목:
    <%= f.text_field :title, class: "form-control", placeholder: "제목을 입력해주세요" %><br>
    내용:
    <%= f.text_area :content, class: "form-control",placeholder: "내용을 입력해주세요" %><br>
    
    <%= f.hidden_field :user_id, :value => current_user.id %>
    <%= f.submit "작성하기", class: "btn btn-success"%>
<% end %>

app/views/posts/edit.html.erb
<%= render partial: "form" %>

app/views/posts/index.html.erb
<div class="jumbotron">
  <h1>글을 작성하고 파일을 올려봅시다.</h1>
  <%= link_to "글쓰기", new_post_path, class: "btn btn-primary btn-lg" %>
</div>

<div class="list-group">
  <% @posts.each do |post| %>
      <%= link_to post.title, post_path(post), class: "list-group-item"%>
  <% end %>
</div>

app/views/posts/new.html.erb
<%= render partial: "form" %>

app/views/posts/show.html.erb
<div class="jumbotron">
  <h1>포스트 상세보기</h1>
  <%= flash[:alert] %>
</div>
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">제목: <%=@post.title%></h3>
  </div>
  <div class="panel-body">
    내용: <%=@post.content%>
  </div>
  <% if current_user.id == @post.user_id %>
      <%= link_to '수정', edit_post_path(@post), class: "btn btn-default btn-sm"%>
      <%= link_to '삭제', post_path(@post), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-default btn-sm"%>
  <% end %>
</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>